arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5  # Changed from 0.005 to 0.5 seconds
  position_only_ik: false  # Changed from True to false for full 6DOF IK